# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all
Jonathan_Swift = User.create!(name: "Jonathan Swift", email: "js@js.com", password: "password")
G_K_Chesterton = User.create!(name: "G K Chesterton", email: "gkc@gck.com", password: "password")
Christopher_Morley = User.create!(name: "Christopher Morley", email: "cm@cm.com", password: "password")
Ann_Plato = User.create!(name: "Ann Plato", email: "ap@ap.com", password: "password")
Francis_Bacon = User.create!(name: "Francis Bacon", email: "fb@fb.com", password: "password")
Guest = User.create!(name: "Guest", email: "guest@guest.com", password: "password")

Story.destroy_all
Jonathan_Swift.stories.create!(title: "A Modest Proposal", content: "It is a melancholy object to those, who walk through this great town, or travel in the country, when they see the streets, the roads and cabbin-doors crowded with beggars of the female sex, followed by three, four, or six children, all in rags, and importuning every passenger for an alms. These mothers instead of being able to work for their honest livelihood, are forced to employ all their time in stroling to beg sustenance for their helpless infants who, as they grow up, either turn thieves for want of work, or leave their dear native country, to fight for the Pretender in Spain, or sell themselves to the Barbadoes.

I think it is agreed by all parties, that this prodigious number of children in the arms, or on the backs, or at the heels of their mothers, and frequently of their fathers, is in the present deplorable state of the kingdom, a very great additional grievance; and therefore whoever could find out a fair, cheap and easy method of making these children sound and useful members of the common-wealth, would deserve so well of the publick, as to have his statue set up for a preserver of the nation.

But my intention is very far from being confined to provide only for the children of professed beggars: it is of a much greater extent, and shall take in the whole number of infants at a certain age, who are born of parents in effect as little able to support them, as those who demand our charity in the streets.

As to my own part, having turned my thoughts for many years, upon this important subject, and maturely weighed the several schemes of our projectors, I have always found them grossly mistaken in their computation. It is true, a child just dropt from its dam, may be supported by her milk, for a solar year, with little other nourishment: at most not above the value of two shillings, which the mother may certainly get, or the value in scraps, by her lawful occupation of begging; and it is exactly at one year old that I propose to provide for them in such a manner, as, instead of being a charge upon their parents, or the parish, or wanting food and raiment for the rest of their lives, they shall, on the contrary, contribute to the feeding, and partly to the cloathing of many thousands.

There is likewise another great advantage in my scheme, that it will prevent those voluntary abortions, and that horrid practice of women murdering their bastard children, alas! too frequent among us, sacrificing the poor innocent babes, I doubt, more to avoid the expence than the shame, which would move tears and pity in the most savage and inhuman breast.

The number of souls in this kingdom being usually reckoned one million and a half, of these I calculate there may be about two hundred thousand couple whose wives are breeders; from which number I subtract thirty thousand couple, who are able to maintain their own children, (although I apprehend there cannot be so many, under the present distresses of the kingdom) but this being granted, there will remain an hundred and seventy thousand breeders. I again subtract fifty thousand, for those women who miscarry, or whose children die by accident or disease within the year. There only remain an hundred and twenty thousand children of poor parents annually born. The question therefore is, How this number shall be reared, and provided for? which, as I have already said, under the present situation of affairs, is utterly impossible by all the methods hitherto proposed. For we can neither employ them in handicraft or agriculture; we neither build houses, (I mean in the country) nor cultivate land: they can very seldom pick up a livelihood by stealing till they arrive at six years old; except where they are of towardly parts, although I confess they learn the rudiments much earlier; during which time they can however be properly looked upon only as probationers: As I have been informed by a principal gentleman in the county of Cavan, who protested to me, that he never knew above one or two instances under the age of six, even in a part of the kingdom so renowned for the quickest proficiency in that art.

I am assured by our merchants, that a boy or a girl before twelve years old, is no saleable commodity, and even when they come to this age, they will not yield above three pounds, or three pounds and half a crown at most, on the exchange; which cannot turn to account either to the parents or kingdom, the charge of nutriments and rags having been at least four times that value.

I shall now therefore humbly propose my own thoughts, which I hope will not be liable to the least objection.


I have been assured by a very knowing American of my acquaintance in London, that a young healthy child well nursed, is, at a year old, a most delicious nourishing and wholesome food, whether stewed, roasted, baked, or boiled; and I make no doubt that it will equally serve in a fricasie, or a ragoust.

I do therefore humbly offer it to publick consideration, that of the hundred and twenty thousand children, already computed, twenty thousand may be reserved for breed, whereof only one fourth part to be males; which is more than we allow to sheep, black cattle, or swine, and my reason is, that these children are seldom the fruits of marriage, a circumstance not much regarded by our savages, therefore, one male will be sufficient to serve four females. That the remaining hundred thousand may, at a year old, be offered in sale to the persons of quality and fortune, through the kingdom, always advising the mother to let them suck plentifully in the last month, so as to render them plump, and fat for a good table. A child will make two dishes at an entertainment for friends, and when the family dines alone, the fore or hind quarter will make a reasonable dish, and seasoned with a little pepper or salt, will be very good boiled on the fourth day, especially in winter.

I have reckoned upon a medium, that a child just born will weigh 12 pounds, and in a solar year, if tolerably nursed, encreaseth to 28 pounds.


I grant this food will be somewhat dear, and therefore very proper for landlords, who, as they have already devoured most of the parents, seem to have the best title to the children.

Infant’s flesh will be in season throughout the year, but more plentiful in March, and a little before and after; for we are told by a grave author, an eminent French physician, that fish being a prolifick dyet, there are more children born in Roman Catholick countries about nine months after Lent, the markets will be more glutted than usual, because the number of Popish infants, is at least three to one in this kingdom, and therefore it will have one other collateral advantage, by lessening the number of Papists among us.

I have already computed the charge of nursing a beggar’s child (in which list I reckon all cottagers, labourers, and four-fifths of the farmers) to be about two shillings per annum, rags included; and I believe no gentleman would repine to give ten shillings for the carcass of a good fat child, which, as I have said, will make four dishes of excellent nutritive meat, when he hath only some particular friend, or his own family to dine with him. Thus the squire will learn to be a good landlord, and grow popular among his tenants, the mother will have eight shillings neat profit, and be fit for work till she produces another child.

Those who are more thrifty (as I must confess the times require) may flea the carcass; the skin of which, artificially dressed, will make admirable gloves for ladies, and summer boots for fine gentlemen.

As to our City of Dublin, shambles may be appointed for this purpose, in the most convenient parts of it, and butchers we may be assured will not be wanting; although I rather recommend buying the children alive, and dressing them hot from the knife, as we do roasting pigs.

A very worthy person, a true lover of his country, and whose virtues I highly esteem, was lately pleased, in discoursing on this matter, to offer a refinement upon my scheme. He said, that many gentlemen of this kingdom, having of late destroyed their deer, he conceived that the want of venison might be well supply’d by the bodies of young lads and maidens, not exceeding fourteen years of age, nor under twelve; so great a number of both sexes in every country being now ready to starve for want of work and service: And these to be disposed of by their parents if alive, or otherwise by their nearest relations. But with due deference to so excellent a friend, and so deserving a patriot, I cannot be altogether in his sentiments; for as to the males, my American acquaintance assured me from frequent experience, that their flesh was generally tough and lean, like that of our school-boys, by continual exercise, and their taste disagreeable, and to fatten them would not answer the charge. Then as to the females, it would, I think, with humble submission, be a loss to the publick, because they soon would become breeders themselves: And besides, it is not improbable that some scrupulous people might be apt to censure such a practice, (although indeed very unjustly) as a little bordering upon cruelty, which, I confess, hath always been with me the strongest objection against any project, how well soever intended.

But in order to justify my friend, he confessed, that this expedient was put into his head by the famous Salmanaazor, a native of the island Formosa, who came from thence to London, above twenty years ago, and in conversation told my friend, that in his country, when any young person happened to be put to death, the executioner sold the carcass to persons of quality, as a prime dainty; and that, in his time, the body of a plump girl of fifteen, who was crucified for an attempt to poison the Emperor, was sold to his imperial majesty’s prime minister of state, and other great mandarins of the court in joints from the gibbet, at four hundred crowns. Neither indeed can I deny, that if the same use were made of several plump young girls in this town, who without one single groat to their fortunes, cannot stir abroad without a chair, and appear at a play-house and assemblies in foreign fineries which they never will pay for; the kingdom would not be the worse.

Some persons of a desponding spirit are in great concern about that vast number of poor people, who are aged, diseased, or maimed; and I have been desired to employ my thoughts what course may be taken, to ease the nation of so grievous an incumbrance. But I am not in the least pain upon that matter, because it is very well known, that they are every day dying, and rotting, by cold and famine, and filth, and vermin, as fast as can be reasonably expected. And as to the young labourers, they are now in almost as hopeful a condition. They cannot get work, and consequently pine away from want of nourishment, to a degree, that if at any time they are accidentally hired to common labour, they have not strength to perform it, and thus the country and themselves are happily delivered from the evils to come.

I have too long digressed, and therefore shall return to my subject. I think the advantages by the proposal which I have made are obvious and many, as well as of the highest importance.


For first, as I have already observed, it would greatly lessen the number of Papists, with whom we are yearly over-run, being the principal breeders of the nation, as well as our most dangerous enemies, and who stay at home on purpose with a design to deliver the kingdom to the Pretender, hoping to take their advantage by the absence of so many good Protestants, who have chosen rather to leave their country, than stay at home and pay tithes against their conscience to an episcopal curate.

Secondly, The poorer tenants will have something valuable of their own, which by law may be made liable to a distress, and help to pay their landlord’s rent, their corn and cattle being already seized, and money a thing unknown.

Thirdly, Whereas the maintainance of an hundred thousand children, from two years old, and upwards, cannot be computed at less than ten shillings a piece per annum, the nation’s stock will be thereby encreased fifty thousand pounds per annum, besides the profit of a new dish, introduced to the tables of all gentlemen of fortune in the kingdom, who have any refinement in taste. And the money will circulate among our selves, the goods being entirely of our own growth and manufacture.

Fourthly, The constant breeders, besides the gain of eight shillings sterling per annum by the sale of their children, will be rid of the charge of maintaining them after the first year.


Fifthly, This food would likewise bring great custom to taverns, where the vintners will certainly be so prudent as to procure the best receipts for dressing it to perfection; and consequently have their houses frequented by all the fine gentlemen, who justly value themselves upon their knowledge in good eating; and a skilful cook, who understands how to oblige his guests, will contrive to make it as expensive as they please.

Sixthly, This would be a great inducement to marriage, which all wise nations have either encouraged by rewards, or enforced by laws and penalties. It would encrease the care and tenderness of mothers towards their children, when they were sure of a settlement for life to the poor babes, provided in some sort by the publick, to their annual profit instead of expence. We should soon see an honest emulation among the married women, which of them could bring the fattest child to the market. Men would become as fond of their wives, during the time of their pregnancy, as they are now of their mares in foal, their cows in calf, or sow when they are ready to farrow; nor offer to beat or kick them (as is too frequent a practice) for fear of a miscarriage.

Many other advantages might be enumerated. For instance, the addition of some thousand carcasses in our exportation of barrel’d beef: the propagation of swine’s flesh, and improvement in the art of making good bacon, so much wanted among us by the great destruction of pigs, too frequent at our tables; which are no way comparable in taste or magnificence to a well grown, fat yearly child, which roasted whole will make a considerable figure at a Lord Mayor’s feast, or any other publick entertainment. But this, and many others, I omit, being studious of brevity.

Supposing that one thousand families in this city, would be constant customers for infants flesh, besides others who might have it at merry meetings, particularly at weddings and christenings, I compute that Dublin would take off annually about twenty thousand carcasses; and the rest of the kingdom (where probably they will be sold somewhat cheaper) the remaining eighty thousand.

I can think of no one objection, that will possibly be raised against this proposal, unless it should be urged, that the number of people will be thereby much lessened in the kingdom. This I freely own, and ’twas indeed one principal design in offering it to the world. I desire the reader will observe, that I calculate my remedy for this one individual Kingdom of Ireland, and for no other that ever was, is, or, I think, ever can be upon Earth. Therefore let no man talk to me of other expedients: Of taxing our absentees at five shillings a pound: Of using neither cloaths, nor houshold furniture, except what is of our own growth and manufacture: Of utterly rejecting the materials and instruments that promote foreign luxury: Of curing the expensiveness of pride, vanity, idleness, and gaming in our women: Of introducing a vein of parsimony, prudence and temperance: Of learning to love our country, wherein we differ even from Laplanders, and the inhabitants of Topinamboo: Of quitting our animosities and factions, nor acting any longer like the Jews, who were murdering one another at the very moment their city was taken: Of being a little cautious not to sell our country and consciences for nothing: Of teaching landlords to have at least one degree of mercy towards their tenants. Lastly, of putting a spirit of honesty, industry, and skill into our shop-keepers, who, if a resolution could now be taken to buy only our native goods, would immediately unite to cheat and exact upon us in the price, the measure, and the goodness, nor could ever yet be brought to make one fair proposal of just dealing, though often and earnestly invited to it.

Therefore I repeat, let no man talk to me of these and the like expedients, till he hath at least some glympse of hope, that there will ever be some hearty and sincere attempt to put them into practice.


But, as to my self, having been wearied out for many years with offering vain, idle, visionary thoughts, and at length utterly despairing of success, I fortunately fell upon this proposal, which, as it is wholly new, so it hath something solid and real, of no expence and little trouble, full in our own power, and whereby we can incur no danger in disobliging England. For this kind of commodity will not bear exportation, and flesh being of too tender a consistence, to admit a long continuance in salt, although perhaps I could name a country, which would be glad to eat up our whole nation without it.

After all, I am not so violently bent upon my own opinion, as to reject any offer, proposed by wise men, which shall be found equally innocent, cheap, easy, and effectual. But before something of that kind shall be advanced in contradiction to my scheme, and offering a better, I desire the author or authors will be pleased maturely to consider two points. First, As things now stand, how they will be able to find food and raiment for a hundred thousand useless mouths and backs. And secondly, There being a round million of creatures in humane figure throughout this kingdom, whose whole subsistence put into a common stock, would leave them in debt two million of pounds sterling, adding those who are beggars by profession, to the bulk of farmers, cottagers and labourers, with their wives and children, who are beggars in effect; I desire those politicians who dislike my overture, and may perhaps be so bold to attempt an answer, that they will first ask the parents of these mortals, whether they would not at this day think it a great happiness to have been sold for food at a year old, in the manner I prescribe, and thereby have avoided such a perpetual scene of misfortunes, as they have since gone through, by the oppression of landlords, the impossibility of paying rent without money or trade, the want of common sustenance, with neither house nor cloaths to cover them from the inclemencies of the weather, and the most inevitable prospect of intailing the like, or greater miseries, upon their breed for ever.

I profess, in the sincerity of my heart, that I have not the least personal interest in endeavouring to promote this necessary work, having no other motive than the publick good of my country, by advancing our trade, providing for infants, relieving the poor, and giving some pleasure to the rich. I have no children, by which I can propose to get a single penny; the youngest being nine years old, and my wife past child-bearing.")



G_K_Chesterton.stories.create!(title: "On Lying In Bed", content: "Lying in bed would be an altogether perfect and supreme experience if only one had a coloured pencil long enough to draw on the ceiling. This, however, is not generally a part of the domestic apparatus on the premises. I think myself that the thing might be managed with several pails of Aspinall and a broom. Only if one worked in a really sweeping and masterly way, and laid on the colour in great washes, it might drip down again on one’s face in floods of rich and mingled colour like some strange fairy rain; and that would have its disadvantages. I am afraid it would be necessary to stick to black and white in this form of artistic composition. To that purpose, indeed, the white ceiling would be of the greatest possible use; in fact, it is the only use I think of a white ceiling being put to.

But for the beautiful experiment of lying in bed I might never have discovered it. For years I have been looking for some blank spaces in a modern house to draw on. Paper is much too small for any really allegorical design; as Cyrano de Bergerac says, “Il me faut des géants” [“I need giants”]. But when I tried to find these fine clear spaces in the modern rooms such as we all live in I was continually disappointed. I found an endless pattern and complication of small objects hung like a curtain of fine links between me and my desire. I examined the walls; I found them to my surprise to be already covered with wallpaper, and I found the wallpaper to be already covered with uninteresting images, all bearing a ridiculous resemblance to each other. I could not understand why one arbitrary symbol (a symbol apparently entirely devoid of any religious or philosophical significance) should thus be sprinkled all over my nice walls like a sort of small-pox. The Bible must be referring to wallpapers, I think, when it says, “Use not vain repetitions, as the Gentiles do.” I found the Turkey carpet a mass of unmeaning colours, rather like the Turkish Empire, or like the sweetmeat called Turkish Delight. I do not exactly know what Turkish Delight really is; but I suppose it is Macedonian Massacres. Everywhere that I went forlornly, with my pencil or my paint brush, I found that others had unaccountably been before me, spoiling the walls, the curtains, and the furniture with their childish and barbaric designs.

. . . . .

Nowhere did I find a really clear space for sketching until this occasion when I prolonged beyond the proper limit the process of lying on my back in bed. Then the light of that white heaven broke upon my vision, that breadth of mere white which is indeed almost the definition of Paradise, since it means purity and also means freedom. But alas! like all heavens, now that it is seen it is found to be unattainable; it looks more austere and more distant than the blue sky outside the window. For my proposal to paint on it with the bristly end of a broom has been discouraged—never mind by whom; by a person debarred from all political rights—and even my minor proposal to put the other end of the broom into the kitchen fire and turn it to charcoal has not been conceded. Yet I am certain that it was from persons in my position that all the original inspiration came for covering the ceilings of palaces and cathedrals with a riot of fallen angels or victorious gods. I am sure that it was only because Michael Angelo was engaged in the ancient and honourable occupation of lying in bed that he ever realized how the roof of the Sistine Chapel might be made into an awful imitation of a divine drama that could only be acted in the heavens.

The tone now commonly taken toward the practice of lying in bed is hypocritical and unhealthy. Of all the marks of modernity that seem to mean a kind of decadence, there is none more menacing and dangerous than the exultation of very small and secondary matters of conduct at the expense of very great and primary ones, at the expense of eternal ties and tragic human morality. If there is one thing worse than the modern weakening of major morals, it is the modern strengthening of minor morals. Thus it is considered more withering to accuse a man of bad taste than of bad ethics. Cleanliness is not next to godliness nowadays, for cleanliness is made essential and godliness is regarded as an offence. A playwright can attack the institution of marriage so long as he does not misrepresent the manners of society, and I have met Ibsenite pessimists who thought it wrong to take beer but right to take prussic acid. Especially this is so in matters of hygiene; notably such matters as lying in bed. Instead of being regarded, as it ought to be, as a matter of personal convenience and adjustment, it has come to be regarded by many as if it were a part of essential morals to get up early in the morning. It is upon the whole part of practical wisdom; but there is nothing good about it or bad about its opposite.

. . . . .

Misers get up early in the morning; and burglars, I am informed, get up the night before. It is the great peril of our society that all its mechanisms may grow more fixed while its spirit grows more fickle. A man’s minor actions and arrangements ought to be free, flexible, creative; the things that should be unchangeable are his principles, his ideals. But with us the reverse is true; our views change constantly; but our lunch does not change. Now, I should like men to have strong and rooted conceptions, but as for their lunch, let them have it sometimes in the garden, sometimes in bed, sometimes on the roof, sometimes in the top of a tree. Let them argue from the same first principles, but let them do it in a bed, or a boat, or a balloon. This alarming growth of good habits really means a too great emphasis on those virtues which mere custom can ensure, it means too little emphasis on those virtues which custom can never quite ensure, sudden and splendid virtues of inspired pity or of inspired candour. If ever that abrupt appeal is made to us we may fail. A man can get used to getting up at five o’clock in the morning. A man cannot very well get used to being burnt for his opinions; the first experiment is commonly fatal. Let us pay a little more attention to these possibilities of the heroic and unexpected. I dare say that when I get out of this bed I shall do some deed of an almost terrible virtue.

For those who study the great art of lying in bed there is one emphatic caution to be added. Even for those who can do their work in bed (like journalists), still more for those whose work cannot be done in bed (as, for example, the professional harpooners of whales), it is obvious that the indulgence must be very occasional. But that is not the caution I mean. The caution is this: if you do lie in bed, be sure you do it without any reason or justification at all. I do not speak, of course, of the seriously sick. But if a healthy man lies in bed, let him do it without a rag of excuse; then he will get up a healthy man. If he does it for some secondary hygienic reason, if he has some scientific explanation, he may get up a hypochondriac.")


Christopher_Morley.stories.create!(title: "On Laziness", content: "To-day we rather intended to write an essay on Laziness, but were too indolent to do so.

The sort of thing we had in mind to write would have been exceedingly persuasive. We intended to discourse a little in favour of a greater appreciation of Indolence as a benign factor in human affairs.

It is our observation that every time we get into trouble it is due to not having been lazy enough. Unhappily, we were born with a certain fund of energy. We have been hustling about for a number of years now, and it doesn’t seem to get us anything but tribulation. Henceforward we are going to make a determined effort to be more languid and demure. It is the bustling man who always gets put on committees, who is asked to solve the problems of other people and neglect his own.

The man who is really, thoroughly, and philosophically slothful is the only thoroughly happy man. It is the happy man who benefits the world. The conclusion is inescapable.

We remember a saying about the meek inheriting the earth. The truly meek man is the lazy man. He is too modest to believe that any ferment and hubbub of his can ameliorate the earth or assuage the perplexities of humanity.

O. Henry said once that one should be careful to distinguish laziness from dignified repose. Alas, that was a mere quibble. Laziness is always dignified, it is always reposeful. Philosophical laziness, we mean. The kind of laziness that is based upon a carefully reasoned analysis of experience. Acquired laziness. We have no respect for those who were born lazy; it is like being born a millionaire: they cannot appreciate their bliss. It is the man who has hammered his laziness out of the stubborn material of life for whom we chant praise and allelulia.

The laziest man we know—we do not like to mention his name, as the brutal world does not yet recognize sloth at its community value—is one of the greatest poets in this country; one of the keenest satirists; one of the most rectilinear thinkers. He began life in the customary hustling way. He was always too busy to enjoy himself. He became surrounded by eager people who came to him to solve their problems. “It’s a queer thing,” he said sadly; “no one ever comes to me asking for help in solving my problems.” Finally the light broke upon him. He stopped answering letters, buying lunches for casual friends and visitors from out of town, he stopped lending money to old college pals and frittering his time away on all the useless minor matters that pester the good-natured. He sat down in a secluded café with his cheek against a seidel of dark beer and began to caress the universe with his intellect.

The most damning argument against the Germans is that they were not lazy enough. In the middle of Europe, a thoroughly disillusioned, indolent and delightful old continent, the Germans were a dangerous mass of energy and bumptious push. If the Germans had been as lazy, as indifferent, and as righteously laissez-fairish as their neighbours, the world would have been spared a great deal.

People respect laziness. If you once get a reputation for complete, immovable, and reckless indolence the world will leave you to your own thoughts, which are generally rather interesting.

Doctor Johnson, who was one of the world’s great philosophers, was lazy. Only yesterday our friend the Caliph showed us an extraordinarily interesting thing. It was a little leather-bound notebook in which Boswell jotted down memoranda of his talks with the old doctor. These notes he afterward worked up into the immortal Biography. And lo and behold, what was the very first entry in this treasured little relic?

Doctor Johnson told me in going to Ilam from Ashbourne, 22 September, 1777, that the way the plan of his Dictionary came to be addressed to Lord Chesterfield was this: He had neglected to write it by the time appointed. Dodsley suggested a desire to have it addressed to Lord C. Mr. J. laid hold of this as an excuse for delay, that it might be better done perhaps, and let Dodsley have his desire. Mr. Johnson said to his friend, Doctor Bathurst: “Now if any good comes of my addressing to Lord Chesterfield it will be ascribed to deep policy and address, when, in fact, it was only a casual excuse for laziness.”
Thus we see that it was sheer laziness that led to the greatest triumph of Doctor Johnson’s life, the noble and memorable letter to Chesterfield in 1775.

Mind your business is a good counsel; but mind your idleness also. It’s a tragic thing to make a business of your mind. Save your mind to amuse yourself with.

The lazy man does not stand in the way of progress. When he sees progress roaring down upon him he steps nimbly out of the way. The lazy man doesn’t (in the vulgar phrase) pass the buck. He lets the buck pass him. We have always secretly envied our lazy friends. Now we are going to join them. We have burned our boats or our bridges or whatever it is that one burns on the eve of a momentous decision.

Writing on this congenial topic has roused us up to quite a pitch of enthusiasm and energy.")


Ann_Plato.stories.create!(title: "Description Of A Desert", content: 'It is difficult to form a correct idea of a desert, without having seen one. It is a vast plain of sands and stones, interspersed with mountains of various sizes and heights, without roads or shelters. They sometimes have springs of water, which burst forth, and create verdant spots.

The most remarkable of deserts is the Sahara. This is a vast plain, but little elevated above the level of the ocean, and covered with sand and gravel, with a mixture of sea shells, and appears like the basin of an evaporated sea.

Amid the desert there are springs of water, which burst forth and create verdant spots, called Oases. There are thirty-two of these which contain fountains, and Date and Palm trees; twenty of them are inhabited. They serve as stopping places for the caravans, and often contain villages.

Were it not for these no human being could cross this waste of burning sand. So violent, sometimes, is the burning wind that the scorching heat dries up the water of these springs, and then frequently, the most disastrous consequences follow.

In 1805, a caravan, consisting of 2,000 persons and 1,800 camels, not finding water at the usual resting place, died of thirst, both men and animals. Storms of wind are more terrible on this desert than on the ocean. Vast surges and clouds of red sand are raised and rolled forward, burying every thing in its way, and it is said that whole tribes have thus been swallowed up.

The situation of such is dreadful, and admits of no resource. Many perish victims of the most horrible thirst. It is then that the value of a cup of water is really felt.

In such a case there is no distinction. If the master has not, the servant will not give it to him; for very few are the instances where a man will voluntarily lose his life to save that of another. What a situation for a man, though a rich one, perhaps the owner of all the caravan! He is dying for a cup of water—no one gives it to him; he offers all he possesses—no one hears him; they are all dying, though by walking a few hours further, they might be saved.

In short, to be thirsty in a desert, without water, exposed to the burning sun, without shelter, is the most terrible situation that a man can be placed in, and one of the greatest sufferings that a human being can sustain; the tongue and lips swell; a hollow sound is heard in the ears, which brings on deafness, and the brain appears to grow thick and inflamed.

If, unfortunately, any one falls sick on the road, he must either endure the fatigue of traveling on a camel, (which is troublesome even to healthy people,) or he must be left behind on the sand, without any assistance, and remain so till a slow death come to relieve him. No one remains with him, not even his old and faithful servant; no one will stay and die with him; all pity his fate, but no one will be his companion.")')


Francis_Bacon.stories.create!(title: "Of Studies", content: "Studies serve for delight, for ornament, and for ability. Their chief use for delight is in privateness and retiring; for ornament is in discourse; and for ability is in the judgment and disposition of business. For expert men can execute, and perhaps judge of particulars, one by one; but the general counsels, and the plots and marshalling of affairs, come best, from those that are learned. To spend too much time in studies is sloth; to use them too much for ornament, is affectation; to make judgment wholly by their rules, is the humor of a scholar. They perfect nature, and are perfected by experience: for natural abilities are like natural plants, that need pruning, by study; and studies themselves, do give forth directions too much at large, except they be bounded in by experience. Crafty men condemn studies, simple men admire them, and wise men use them; for they teach not their own use; but that is a wisdom without them, and above them, won by observation.

Read not to contradict and confute; nor to believe and take for granted; nor to find talk and discourse; but to weigh and consider. Some books are to be tasted, others to be swallowed, and some few to be chewed and digested; that is, some books are to be read only in parts; others to be read, but not curiously; and some few to be read wholly, and with diligence and attention. Some books also may be read by deputy, and extracts made of them by others; but that would be only in the less important arguments, and the meaner sort of books, else distilled books are like common distilled waters, flashy things. Reading maketh a full man; conference a ready man; and writing an exact man. And therefore, if a man write little, he had need have a great memory; if he confer little, he had need have a present wit: and if he read little, he had need have much cunning, to seem to know, that he doth not. Histories make men wise; poets witty; the mathematics subtile; natural philosophy deep; moral grave; logic and rhetoric able to contend.

Abeunt studia in mores.
[“practices zealously pursued pass into habits.”—Merriam-Webster definition]

Nay, there is no ston[e] or impediment in the wit, but may be wrought out by fit studies; like as diseases of the body, may have appropriate exercises. Bowling is good for the stone and reins; shooting for the lungs and breast; gentle walking for the stomach; riding for the head; and the like. So if a man’s wit be wandering, let him study the mathematics; for in demonstrations, if his wit be called away never so little, he must begin again. If his wit be not apt to distinguish or find differences, let him study the Schoolmen; for they are cymini sectores. If he be not apt to beat over matters, and to call up one thing to prove and illustrate another, let him study the lawyers’ cases. So every defect of the mind, may have a special receipt.")


Topic.destroy_all
news = Topic.create!(title: "News")
essays = Topic.create!(title: "Essays")
fiction = Topic.create!(title: "Fiction")
election = Topic.create!(title: "Election")
